### PR TITLE
updating AEP link

### PR DESCRIPTION
**Pull request by joemcl**
updated to https://api.mobilize.io/v1/

### CODE REVIEW

**Comment by kylehg** [comment]
Hey @joemcl ! That endpoint is actually for Mobilize.io, which is a different service and company than us, MobilizeAmerica. I know this is a confusing distinction, and appreciate you looking out!

**Comment by joemcl** [comment]
OK @kylehg but Mobilize.io and MobilizeAmerica are related companies, correct? And in any event - this link does not work - `https://api.mobilize.us/v1` . What is the correct AEP?

**Comment by kylehg** [comment]
No, we're actually entirely different companies I'm afraid! We are a progressive event + volunteer platform, Mobilize.io makes a groups tool. And that is the correct AEP, we just don't serve a top-level response. You need a supported endpoint like https://api.mobilize.us/v1/events

**Comment by joemcl** [comment]
OK thanks @kylehg got it.

**Pull request closed without merging**
